In [ ]:
from models.pre_processing import PreProcessing
from models.vectorization_model import VectorizationModel


In [11]:
text = "A inteligência artificial está transformando o mund0, com n0vas aplicações; Algoritmos de aprendizado de máquina sã0 essenciais para isso; A automação robótica é um dos camp0s mais interessantes da tecnologia hoje em-dia; O! processamento de8linguagem natural (PLN) permite que computadores compre+endam a linguagem humana; Chatbots e assistentes de voz sã0 um bom exemplo do PLN em ação."

In [22]:
from gensim.models import Word2Vec
import numpy as np
model = Word2Vec(sentences=text, vector_size=100, window=5, min_count=1, workers=4, sg=1)
for setence in text:

    response = np.mean(model.wv[setence])
    break

In [23]:
response

0.00035240795

In [12]:
pre_processing = PreProcessing()
vetorization_model = VectorizationModel()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mbela\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
text = pre_processing.pipeline(text)
text

[['intelig', 'artific', 'transform', 'mundé', 'nev', 'aplic'],
 ['algoritm', 'aprend', 'máquin', 'sã', 'essenc'],
 ['autom', 'robó', 'campé', 'interess', 'tecnolog', 'hoj', 'dia'],
 ['process',
  'deslingu',
  'natur',
  'plá',
  'permit',
  'comput',
  'compreend',
  'lingu',
  'human'],
 ['chat', 'assist', 'voz', 'sã', 'bom', 'exempl', 'plá', 'açã']]

In [14]:
binary_vectors = vetorization_model.binary_aproach(text)
binary_vectors

[array(['algoritm', 'aplic', 'aprend', 'artific', 'assist', 'autom', 'açã',
        'bom', 'campé', 'chat', 'compreend', 'comput', 'deslingu', 'dia',
        'essenc', 'exempl', 'hoj', 'human', 'intelig', 'interess', 'lingu',
        'mundé', 'máquin', 'natur', 'nev', 'permit', 'plá', 'process',
        'robó', 'sã', 'tecnolog', 'transform', 'voz'], dtype=object),
 array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64),
 array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1

In [15]:
bow_vectors = vetorization_model.bow_aproach(text)
bow_vectors

[array(['algoritm', 'aplic', 'aprend', 'artific', 'assist', 'autom', 'açã',
        'bom', 'campé', 'chat', 'compreend', 'comput', 'deslingu', 'dia',
        'essenc', 'exempl', 'hoj', 'human', 'intelig', 'interess', 'lingu',
        'mundé', 'máquin', 'natur', 'nev', 'permit', 'plá', 'process',
        'robó', 'sã', 'tecnolog', 'transform', 'voz'], dtype=object),
 array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64),
 array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1

In [16]:
tf_idf_vectors = vetorization_model.tf_idf_aproach(text)
tf_idf_vectors

[array(['algoritm', 'aplic', 'aprend', 'artific', 'assist', 'autom', 'açã',
        'bom', 'campé', 'chat', 'compreend', 'comput', 'deslingu', 'dia',
        'essenc', 'exempl', 'hoj', 'human', 'intelig', 'interess', 'lingu',
        'mundé', 'máquin', 'natur', 'nev', 'permit', 'plá', 'process',
        'robó', 'sã', 'tecnolog', 'transform', 'voz'], dtype=object),
 array([0.        , 0.40824829, 0.        , 0.40824829, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.40824829, 0.        ,
        0.        , 0.40824829, 0.        , 0.        , 0.40824829,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.40824829, 0.        ]),
 array([0.46369322, 0.        , 0.46369322, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ,

In [17]:
word2vec_vectors = vetorization_model.word2vec_aproach(text)
word2vec_vectors

[{'word': 'intelig',
  'vector': array([ 6.4122751e-03, -8.9508612e-03, -7.3429774e-03, -1.7483676e-03,
          1.6955255e-03, -1.0352057e-03, -5.2053290e-03,  6.5782177e-03,
          8.7826597e-03, -7.4135298e-03,  9.8067494e-03,  7.3652966e-03,
         -7.4582323e-03, -1.8976372e-03,  4.2521115e-03,  7.0585934e-03,
         -3.6642274e-03, -6.9745216e-03,  4.7208932e-03, -9.0424940e-03,
         -5.8530443e-03, -1.2788851e-03,  5.4769972e-03, -5.6835311e-03,
          4.7853016e-03, -4.3346270e-04,  2.6679533e-03,  6.4052534e-03,
          1.4161465e-03,  7.7077015e-03, -3.2646907e-04, -8.2628215e-03,
          9.1788629e-03, -4.8582479e-03,  4.7221654e-03, -3.8997133e-03,
         -7.3261028e-03, -6.5181949e-03,  4.6760594e-03, -6.5431546e-04,
          1.4604749e-03, -8.9297043e-03, -5.1482995e-03, -6.0543399e-03,
          8.4154978e-03, -8.6997123e-03,  5.0227703e-03, -8.6111994e-04,
          1.8932854e-04,  8.7981354e-03, -3.5822676e-03, -6.9361860e-03,
          7.6325715e

In [18]:
fasttext_vectors = vetorization_model.fasttext_aproach(text)
fasttext_vectors

[{'word': 'intelig',
  'vector': array([ 6.9594193e-05,  2.2382087e-03, -2.2263508e-03, -5.6514418e-04,
          5.3045701e-04, -4.6475074e-04,  7.1429044e-05,  3.3465429e-04,
          8.2316919e-04,  6.5921724e-04, -7.5001089e-04,  1.7335964e-03,
          6.8807701e-04,  1.5178770e-03,  6.6741661e-04, -1.6017882e-04,
          1.4648808e-04, -6.6558347e-04, -3.5514424e-04, -5.7437370e-04,
         -2.6173557e-03, -2.4310545e-04, -4.6531638e-04, -1.7630984e-03,
         -1.8224318e-03, -2.1440338e-03,  1.4379494e-03, -9.7588776e-04,
          1.0682698e-03, -3.1418455e-04, -7.3002832e-04, -7.5996626e-04,
         -1.7939048e-03, -1.3890638e-03, -3.0567186e-04, -4.9044559e-04,
          1.5223447e-04, -2.5601912e-04,  6.9942465e-04, -1.0460408e-03,
          9.2495832e-04, -2.1363739e-03, -9.6675626e-04,  8.9205074e-04,
          6.4475188e-04,  8.6506415e-04, -1.5896753e-03,  5.3691363e-04,
          5.7538721e-04,  1.8653537e-04, -3.3544924e-04,  5.7719171e-04,
         -1.9807913e